### ISSUE TITLE
How to get completions for helper functions?

### ISSUE THREAD

**Issue by lokesh-krishna** [R-nvim/cmp-r#8]
When using functions like `select()`, is there something I'm missing about getting completions for helper functions such as `starts_with()`, `ends_with()` and `contains()`? Presently I only get variables as completions within the function. 

![image](https://github.com/R-nvim/cmp-r/assets/20235646/5e8edea9-aac2-41dd-be0e-a4a4a1174bbb)

I know this isn't an issue but the repo doesn't have discussions enabled so posted this here. Sorry 🙈

**Comment by jalvesaq** [comment]
We can enable the Discussions...

The options to configure this are `fun_data_1` and `fun_data_2`, as explained in the README.

Maybe you will get the problem fixed by adding more function names to either of these two lists; maybe we should add them by default. I still don't use many of `dplyr` functions, but @PMassicotte may have an opinion on what we should do.

**Comment by PMassicotte** [comment]
It works on my side.

![image](https://github.com/R-nvim/cmp-r/assets/4519221/d784cbb8-1ee2-42a9-bd77-1a0be712c30e)

The thing is that you have to "force" it by using `ctrl-space`/

**Comment by lokesh-krishna** [comment]
Where does this *forcing* it come from? <kbd>Ctrl</kbd>+<kbd>Space</kbd> is my key combo to switch input language so that's what happens when I do it.

**Comment by jalvesaq** [comment]
I have this in mappings of `cmp`, and I believe that @PMassicotte has the same:

```
  ['<C-Space>'] = cmp.mapping.complete(),
```

Before `<Space>` was included among the trigger characters of `cmp-nvim-r`, the problem was that we had to force the completion to get suggestions of arguments; now the problem is the opposite: we have to force the completion to get new suggestions after typing at least one letter.

**Comment by PMassicotte** [comment]
I was typing the same, you were faster :)

**Comment by PMassicotte** [comment]
One thing I noticed, it that is I enter _directly_ in the function, completion will not trigger automatically. However, if I move the cursor directly in the `()` and switch to `insert `, the autocomplete will work:

![Peek 2024-03-13 10-29](https://github.com/R-nvim/cmp-r/assets/4519221/af38cab9-9529-49f7-9504-ac84e54f82b2)

**Comment by PMassicotte** [comment]
Basically, going in normal and then in insert mode inside parenthesis will make the autocomplete works without having to use ctrl-space.

**Comment by lokesh-krishna** [comment]
It does indeed! Thanks a lot both of you!
